
set(LIBNAME libmfx)

file(GLOB VERSION_FILE ${CMAKE_SOURCE_DIR}/tools/depends/target/${LIBNAME}/LIBMFX-VERSION)
file(STRINGS ${VERSION_FILE} VER)

string(REGEX MATCH "VERSION=[^ ]*$.*" LIBMFX_VER "${VER}")
list(GET LIBMFX_VER 0 LIBMFX_VER)
string(SUBSTRING "${LIBMFX_VER}" 8 -1 LIBMFX_VER)

string(REGEX MATCH "BASE_URL=([^ ]*)" LIBMFX_BASE_URL "${VER}")
list(GET LIBMFX_BASE_URL 0 LIBMFX_BASE_URL)
string(SUBSTRING "${LIBMFX_BASE_URL}" 9 -1 LIBMFX_BASE_URL)

set(LIBMFX_URL ${LIBMFX_BASE_URL}/archive/refs/tags/${LIBMFX_VER}.tar.gz)

if(CORE_SYSTEM_NAME STREQUAL windowsstore)
  set(LIBMFX_ADDITIONAL_ARGS "-DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}" "-DCMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION}")
endif()

set(LIBMFX_BASE_BUILD_DIR ${CMAKE_BINARY_DIR}/${CORE_BUILD_DIR}/${LIBNAME})

set(LIBMFX_LIBRARY ${LIBMFX_BASE_BUILD_DIR}/lib/${LIBNAME}${CMAKE_STATIC_LIBRARY_SUFFIX})
set(LIBMFX_INCLUDE_DIR ${LIBMFX_BASE_BUILD_DIR}/include)

ExternalProject_Add(${LIBNAME}
  URL ${LIBMFX_URL}
  DOWNLOAD_DIR ${LIBMFX_BASE_BUILD_DIR}/download
  DOWNLOAD_NAME ${LIBNAME}-${LIBMFX_VER}.tar.gz
  PREFIX  ${LIBMFX_BASE_BUILD_DIR}
  PATCH_COMMAND ${CMAKE_COMMAND} -E copy
				${CMAKE_SOURCE_DIR}/tools/depends/target/libmfx/CMakeLists.txt
				<SOURCE_DIR>
  CMAKE_ARGS
    ${LIBMFX_ADDITIONAL_ARGS}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX:PATH=${LIBMFX_BASE_BUILD_DIR}
  BUILD_COMMAND 
    ${CMAKE_COMMAND} --build ${LIBMFX_BASE_BUILD_DIR}/src/${LIBNAME}-build --config $<CONFIG>
  INSTALL_COMMAND
    ${CMAKE_COMMAND} --install ${LIBMFX_BASE_BUILD_DIR}/src/${LIBNAME}-build --config $<CONFIG>
  BUILD_BYPRODUCTS ${LIBMFX_LIBRARY}
)
set_target_properties(${LIBNAME} PROPERTIES FOLDER "External Projects")

set(LIBMFX_LIBRARIES ${LIBMFX_LIBRARY})
set(LIBMFX_INCLUDE_DIRS ${LIBMFX_INCLUDE_DIR})
set(LIBMFX_DEFINITIONS -DHAVE_LIBMFX=1)

set(LIBMFX_FOUND 1 CACHE BOOL "${LIBNAME} found" FORCE)
